[phases.setup]
nixPkgs = ['python39', 'ffmpeg']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT app:app' 